# Generated by Django 3.0.5 on 2026-05-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_contactfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFeedback',
        ),
    ]
